# Lightweight Node.js image
FROM node:18-alpine

# App directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy app source
COPY . .

# App port
EXPOSE 3000

# Start app
CMD ["node", "app.js"]
